set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Add all your plugins here (note older versions of Vundle used Bundle instead of Plugin)
Plugin 'vim-scripts/indentpython.vim'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'tpope/vim-fugitive'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required


" Custom Vim config
syntax on
set encoding=utf8
set hls
set nu
set ru
map <F5> :w<cr>:!python %<cr>
set fileencodings=utf8,gbk
set ic "incsearch
let python_highlight_all=1
set clipboard=unnamed

" indent 
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    "\ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix

au BufNewFile,BufRead *.js,*.html,*.css
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2


highlight BadWhitespace ctermbg=red guibg=darkred
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/
" Enablefolding
set foldmethod=indent
set foldlevel=99

" words number limit
highlight OverLength ctermbg=red ctermfg=white guibg=#592929 
match OverLength /\%81v.\+/
" Map
map +y :w !pbcopy<cr><cr> 
map +p :r !pbpaste<cr><cr> 
"map <C-]> ddp
"map <C-[> ddkP
"map <C-a> <Esc>ggVG
"map <C-.> :res +1<cr><cr>
"map <C-,> :res -1<cr><cr>
"map <C-]> :vertical res +1<cr><cr>
"map <C-[> :vertical res -1<cr><cr>
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

